version: '2'
services:
  add:
    build:  ./add
    ports:
      -  "5001:5000"
  multiply:
    build: ./multiply
    ports:
      -  "5002:5000"
  substract:
    build: ./substract
    ports:
      -  "5003:5000"
  divide:
    build: ./divide
    ports:
      -  "5004:5000"
  rproxy:
    build: ./rproxy
    ports:
      -  "8080:80"