---
- hosts: all
    vars:
        docker_opts: >
            -H unix://
            -H tcp://0.0.0.02375
	        --log-level=debug
    remote_user: ubuntu
    become: yes
    become_method: sudo
    roles:
    - angstwad.docker.ubuntu